name: Release Test

on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  release-tag:
    name: Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: show release tag
        run: echo ${GITHUB_REF#refs/*/release-}
