name: "Testing GHA"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: false
jobs:
  failures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: main
          fetch-depth: 0  # needed to compare logs
      - name: Initialize mandatory git config
        run: |
          git config user.name 'Sketchings GHA'
          git config user.email 'gha@sketchings.com'
      - name: Merge main back to develop to ensure any changes are brought back
        id: merge-dev
        continue-on-error: true
        run: |
          git checkout conflict
          git merge main
      - name: Failure note
        if: always()
        run: echo "${{ steps.merge-dev.outputs }}"
